---
title: "Data Visualization Handout"
author: "Coleridge"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: 
    margin_references: true
    toc: true
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
library(yaml)
library(tidyverse)
library(magrittr)
setwd("/Users/sophierand/Desktop/ada-tdc-2020")
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)

code_snips_file <-"/Users/sophierand/Desktop/ada-tdc-2020/code_snips.yml"
code_snips_list <- yaml::read_yaml(code_snips_file, fileEncoding = "UTF-8")

code_snips <- as.data.frame(matrix(unlist(code_snips_list), nrow=length(code_snips_list), byrow=TRUE))
colnames(code_snips) <- names(code_snips_list[[1]])
```

# Introduction

The goal of the Data Viz - viz what we made in exploration
We will answer the following questions:

1.  What are different measures of the TANF experience?


## Lesson Structure

The lesson is given over the course of two days - Concepts of Data Visualization and Applications of Data Exploration. 

```{marginfigure, echo=TRUE}
**Materials**:  
1. Data Visualization Video Lecture  
2. `Data Visualization.ipynb`  
```

This handout mirrors the content in the Data Exploration notebook lesson which you can access only in the Administrative Data Research Facility (ADRF). **There is no sensitive data anywhere in this document.** It is a handy reference to use as you step through the lesson in the ADRF, and to refer back to in the future.

Each section has:   

- <span style="color:green;font-weight: bold; ">Guiding Questions</span>, summarized at the top of the section and dispersed throughout the document in <span style="color:green; ">green</span>.
- <span style="color:blue;font-weight: bold; ">Ask Yourself Questions</span>, quick, bite-sized questions to jog your brain and make sure we're all on the same page. in <span style="color:blue; ">blue</span>.
- <span style="color:red;font-weight: bold; ">Checkpoints</span>,  which are mini-exercises for you to complete, to be reviewed during "in-class" time. They are included in each section in <span style="color:red; ">red</span>.

`r margin_note('these come from the syllabus')`

## Learning Objectives and Outcomes

**Concepts of Data Visualization**

1.   Become familiar with ...

**Applications of Data Visualization**`r margin_note('data_visualization.ipynb')`

1.   Become comfortable with ggplot2
1.   apply learnings from **Concepts of Data Viz**.  


# R Setup and Connection to Database

Load libraries   

```yaml
library(ggplot2)
library(tidyverse)
library(DBI)
library(RPostgreSQL)
```

Establish Database Connection

```yaml
`r code_snips$code[code_snips$title=="connect_db"]`

```

# Individual
## Summary Statistics: TANF

<span style="color:green;font-weight: bold;">Guiding Questions:</span>  

For individuals who had a spell ending in 2016 Q4, we want to visualize stats created in Data Exploration:    

1.  Visualize spell length distribution of spell lengths amongst individuals in our cohort?
1.  Visualize spell lengths at the 10th, 25th, 50th, 75th and 90th percentiles?


<span style="color:green; ">What is the distribution of spell lengths amongst individuals in our cohort?</span>

We regenerate our spell values. 

Pause to cover saving values within the ADRF. R has a convenient `RData` format that we can save and bring back into our environment. 

# ?
**Questions** that weren't answered in data exploration but maybe should be here?
- what is the distribution of TANF leavers holding jobs, by geography?



The question is asking us about spell lengths, so we aggregate to count the number of persons with a spell of a given length.

```{marginfigure echo = TRUE} 
The column `tanf_spell_months` has the number of months in that spell.
```

```yaml
`r code_snips$code[code_snips$title=="spell_length_dist_query"]`

`r code_snips$code[code_snips$title=="spell_length_dist"]`

```

We can use `min` and `max` to look at the range of values. We could have done this in SQL also, but since we have the dataframe handy, let's run these quick R commands.

```{marginfigure echo = TRUE} 
We use the `$` sign notation to specify the `length` column, which is the column we're looking for descriptives on. 
  
```

```yaml
min(spell_count_df$length)
max(spell_count_df$length)

```


<span style="color:green; ">What is the spell length at the 25th percentile?</span>


We use the `SQL` function `percentile_cont` to calculate spell lengths at the 25th percentile. There are R functions, like `quantile`, that can be used to calculate percentiles, but we conduct the manipulation with SQL to preserve compute resources.

```yaml
`r code_snips$code[code_snips$title=="spell_length_25tile"]`

```

<span style="color:green; ">What are the spell lengths at the 10th, 25th, 50th, 75th and 90th percentiles?</span>

We can extend the query to calculate other percentile values, and use `unnest` function to see the percentile value with the percentile.

```yaml
`r code_snips$code[code_snips$title=="spell_length_percentiles"]`

```

### <span style="color:red;">CHECKPOINT 3</span>
Calculate spell lengths at different percentiles for the 2009 Q1 Cohort.

Modify the query used to calculate spell length at the 10th, 25th, 50th, 75th and 90th percentile for the cohort exiting TANF in Q1 of 2009.

<ol type="a">
  <li>Parameterize the query with `sprintf`, adding a placeholder for the table.</li>
  <li>Regenerate the query for the 2009 Q1 cohort and retrieve new results from the database.</li>
  
_Solution_
3a
```yaml
`r code_snips$code[code_snips$notebook == "data_exploration" & code_snips$title=="checkpoint2a_solution"]`

```
3b
```yaml
`r code_snips$code[code_snips$notebook == "data_exploration" & code_snips$title=="checkpoint2a_solution"]`

```


```yaml
tbl <- tanf_2009q1

base_query <- "SELECT unnest(
                   percentile_cont(array[0.1,0.25,0.5,0.75,0.9]) 
                   WITHIN GROUP (ORDER BY tanf_spell_months)
                ) AS months,
                unnest(array[0.1,0.25,0.5,0.75,0.9]) as percentile_value
FROM ada_tdc_2020.%s"

query <- sprintf(base_query,tbl)
```

## Summary Statistics: Wages

**Guiding Questions:**     

We are interested in the earnings and employment characteristics of TANF leavers in their 1st and 5th quarters post-exit.
```{marginfigure echo = TRUE}
Introduce `sprintf` function for making queries flexible by creating a placeholder for `yr_quarter` and the table name to calculate distribution of earnings in both cohorts, 1st and 5th quarter post exit   
```
    
    
1.  What is the shape/form of the wage tables?  
1.  How many total jobs did leavers hold in the 1st and 5th quarter post-exit?   
1.  How many individuals were working those jobs?  
1.  What was the distribution of wages in the 1st and 5th quarter post-exit?  
1.  What is the employment and earnings (number of jobs, total wages) of individuals in our 2016 Q4 cohort in the quarter after exit?
1.  What was the proportion of TANF individuals with a job in the 8 quarters after their exit?
1.  What was the proportion of TANF individuals with a stable job in the 8 quarters after their exit? `r margin_note('in 2019, this was how many had it in the year 2017, but i didnt see a calculation that filtered just to this year')`
1.  How many TANF individuals do not have available wage data in our cohort?


**Tables:**
These calculations rely on `ada_tdc_2020.tanf_wage_<year>q<quarter>` which contain wage records for individuals in the corresponding cohort from the quarter of exit until 8 quarters post-exit.
`r margin_note('we may want to talk over this one/confirm. based on 2019 tdc')`


First, we preview the data in the wage cohort tables.

```yaml
dbGetQuery(con, "SELECT * FROM ada_tdc_2020.wage_2016q4 limit 5;)
```
<span style="color:green; "> How many total jobs did leavers hold in the 1st and 5th quarter post-exit?</span>

```{marginfigure, echo=TRUE}
Aggregate the total number of jobs with `count(*)`, since each row is a job. Group by 1st and 5th quarter after exit (Q1 2017 and Q1 2018, respectively).
```

```yaml
query <- "SELECT
job_yr_q, count(*)
FROM ada_tdc_2020.wage_2016q4
WHERE job_yr_q in ('2017-01-01', '2018-01-01')
GROUP BY job_yr_q
ORDER BY job_yr_q asc"
```
   
<span style="color:green; ">How many persons were working those jobs?</span>
```{marginfigure, echo=TRUE}
Aggregate the total number of persons with `count(distinct(ssn))`, since each row is a job and any individual ssn may have multiple jobs. Group by 1st and 5th quarter after exit (Q1 2017 and Q1 2018, respectively).
```

```yaml
query <- "SELECT
job_yr_q, count(distinct(ssn))
FROM ada_tdc_2020.wage_2016q4
WHERE job_yr_q in ('2017-01-01', '2018-01-01')
GROUP BY job_yr_q
ORDER BY job_yr_q asc"
```

<span style="color:green; ">What is the distribution of wages in the 1st quarter after exit?</span>

```{marginfigure, echo=TRUE}
Calculate percentiles at the 10th, 25th, 50th, 75th and 90th percentiles using the PostgreSQL function `percentile_cont` in the 1st quarter after exit. 
```

```yaml
query <- "SELECT unnest(
                   percentile_cont(array[0.1,0.25,0.5,0.75,0.9]) 
                   WITHIN GROUP (ORDER BY wages)
                ) AS earnings_value,
                unnest(array[0.1,0.25,0.5,0.75,0.9]) as percentile_value
FROM ada_tdc_2020.wage_2016q4
WHERE job_yr_q = '2017-01-01'
```
```{marginfigure, echo=TRUE}
**Checkpoint 3 Learning Objectives**:     
Adding multiple placeholders in different places in the SQL query using `sprintf`
```

### <span style="color:red;">CHECKPOINT 3</span>

Modify the queries using the `sprintf` function to make it easy to re-run the queries to create employment measures for the 2009 cohort. 

Modify the queries for these measures:
<ol type="a">
  <li>Number of jobs</li>
  <li>Number of people working those jobs</li>
  <li>Distribution of earnings in a quarter after exit (you will need 2 placeholders - table and quarter). </li>
</ol>

_Solution_

3a
```yaml
`r code_snips$code[code_snips$notebook == "data_exploration" & code_snips$title=="checkpoint3a_solution"]`

```
3b

3c

```{marginfigure, echo=TRUE}
**Checkpoint 3 Learning Objectives**:   
Compare distribution of earnings in different cohorts and quarters since exit, using the parameterized query created in **Checkpoint 2**
```

<span style="color:red; font-weight: bold;">CHECKPOINT 3:</span>
With the parameterized query created in **Checkpoint 2**, calculate the distribution of earnings for:  
- 2016 Q4 Cohort, 5 months post-exit  
- 2009 Q1 Cohort, 1 month post-exit  
- 2009 Q1 Cohort, 5 months post-exit  


From now on, we will parameterize all SQL queries where we can, since the goal of our analyses is to compare two cohorts at different points after they exit TANF.

<span style="color:green; ">What is the employment and earnings (number of jobs, total earnings) of individuals in our cohort?</span>

Calculate number of jobs and total wages per person in a given quarter post-exit. In the notebook, we do this only for the first 100 rows to reduce computational power needed. We filter to look at the 1st quarter post-exit with the `year` and `quarter` columns (intead of `job_yr_q`) to demonstrate use of the `%d` placeholder.



```yaml
`r code_snips$code[code_snips$title=="num_wage_jobs_by_ssn_input"]`

`r code_snips$code[code_snips$title=="num_wage_jobs_by_ssn_base_query"]`

`r code_snips$code[code_snips$title=="num_wage_jobs_by_ssn_query"]`

```

We just saw a non-random sample of the number of jobs per person. Now, we calculate a distribution to give us a fuller picture.`r margin_note('i did a distribition on this - it wasnt in the tdc 2019 notebook')`

<span style="color:green; ">What is the distribution of employment and earnings (number of jobs, total wages) of individuals in our cohorts?</span>


```yaml
`r code_snips$code[code_snips$title=="dist_wages_num_jobs_input"]`

`r code_snips$code[code_snips$title=="dist_wages_num_jobs_base_query"]`

`r code_snips$code[code_snips$title=="dist_wages_num_jobs_query"]`

```

Now we turn to looking at the participation of our TANF cohorts in the job market. 

<span style="color:green; ">Among TANF leavers in our cohort, what was the proportion who had a job at any time during the 8 quarters post-exit?</span>  

First we calculate the number of individuals who had any employment in the wages. This will be the numerator. 
```yaml
`r code_snips$code[code_snips$title=="num_tanf_employed"]`

```

Then we calculate the denominator, # individuals in the exit cohort, to find the proportion amongst all TANF leavers. 
```yaml
`r code_snips$code[code_snips$title=="num_tanf"]`

`r code_snips$code[code_snips$title=="rate_tanf_employed"]`

```

Now we will repeat these proportion calculations, but look at the _stably employed_. What do we mean when we say stable employment? There are a number of measures that speak to the stability of employment: full quarter employment, full year employment, or employment earning over a certain threshold. Here, we will calculate full quarter employment, meaning employment at the same firm for 3 consecutive quarters. This is a `CROSS JOIN` and in order to parameterize, we can still use `sprintf` but the placeholder is `%1$s` instead of `%s`. We also use the `rep` function to generate the input to `sprintf`. See [table_creation](table_creation.html) for more. 

<span style="color:green; ">Among all TANF leavers, what was the proportion of TANF individuals with a stable job at any time during the 8 quarters post-exit? Among employed TANF leavers, what was the proportion who were stably employed?</span>
First we calculate the number of individuals who had three consecutive quarters of employment with the same employer. This will be the numerator. 
```yaml

`r code_snips$code[code_snips$title=="num_stable_employed"]`

```

Then we use the values calculated earlier as the denominators. First, we calculate the proportion amongst all employed TANF leavers. 

```yaml
`r code_snips$code[code_snips$title=="rate_stable_employed"]`

```

Then we calculate the proportion amongst all TANF leavers. 
```yaml

`r code_snips$code[code_snips$title=="rate_stable_tanf"]`

```


<span style="color:red; font-weight: bold;">CHECKPOINT 4:</span>
We just calculated full quarter employment for the 2016 Q4 cohort. Now calculate it for the 2009 Q1 cohort.
`r margin_note('come up with a better checkpoint?')`

# Employer
## Summary Statistics: Employer Characteristics

**Guiding Questions:**  

We want to look at characteristics of firms that employ TANF leavers and all employers. TANF Employers are those employers who had at least one ssn from our TANF cohorts in their wage records. 

1.  What is the employment (total, stable) of firms employing TANF leavers?
1.  What is the payroll/earnings (total, average, stable) of these firms?
1.  In which industries do leavers find stable employment?
1.  Other measures of (turnover, earnings of workers in different percentiles)
    
First let's take a quick look the form of the employer characteristics tables:

<span style="color:green; ">What is the employment (total and stable) of employers?</span>
<span style="color:green; ">In which industries do leavers find stable employment?</span>


# SCRAP
```{marginfigure ECHO = TRUE}
**Columns**
  
`uiacct` - firm identifier 
`naics_3_digit` - NAICS code indicating industry type
`size` - # unique SSNs employed at the firm in the first quarter post-exit
```


We begin looking at characteristics of the firms that employ TANF leavers in our cohorts. The tables we will read from are `ada_tdc_2020.tanf_2016q4_empl` and `ada_tdc_2020.tanf_2009q1_empl`.

<span style="color:green; ">In which industries do leavers find stable employment?</span>

```yaml
cohort <- "2016q4"

base_query <- "SELECT *
FROM ada_tdc_2020.tanf_%s_empl
limit 100;


query <- sprintf(base_query, cohort)

df <- dbGetQuery(con, query)
```

We will answer this by aggregating with the `group_by` and `count` functions from `dplyr` (part of the `tidyverse`). This is our first time aggregating in R - all previous aggregations were done in SQL.

Pipe operator `%>%`

```yaml
df %>% dplyr::group_by(naics_3_digit) %>% count()
```
<span style="color:green; ">How many individuals does the firm employ?</span>

Again we will answer this using R - specifically the `quantile` function from the `stats` library.

```yaml
stats::quantile(df$size, probs = c(0.1,0.25,0.5,0.75,0.9))

```
**I'm pretty sure the remaining questions below do NOT go in data exploration - instead, ML prep like OSU**
1.  How many individuals does the firm employ? Total? `r margin_note('julia included a question about how many ppl does the firm stably employ - just want to make sure that belongs in data exploration. confirm that these earnings measures for the firm side should be here - i think they are in ML prep in OSU')`
1.  What are the wages paid by the firm? Calculate total, average and stable wages.   
1.  Other measures (turnover, earnings of workers in different industries)    


miscellaneous stuff from notebooks I was referencing  


- for how long have they been recieving benefits?  
- caan we find out how much each individual was making and how many jobs they had in 2016 Q4?
- what was the proportion of TANF individuals with a stable job in 2017?
- how many TANF individuals do not have available wage data in our cohort?

NOte that we dont have a QWI notebook (should we?)
- \# of jobs by post-exit quarter (1st and 5th)   
    - \# persons working those jobs by post-exit quarter (1st and 5th)   
    - Distribution of wages in 1st quarter post-exit   
    - \# of jobs per ssn    
    - Distribution of \# of jobs per ssn      

